const portfolioData = [
  {
    id: 1,
    title: 'VUE 포트폴리오',
    desc: 'VUE 기반 포트폴리오 사이트입니다.',
    skill: 'Vue, Router, CSS, JS',
    role: '개인 작업',
    day: '3',
    img: '/img/Portfolio1.png',
    url: 'https://portfolio-azure-ten-57.vercel.app',
  },
  {
    id: 2,
    title: '코딩작품2',
    desc: '두번째작업물입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '3',
    img: 'https://cdn.stocksnap.io/img-thumbs/960w/art-people_GWDEXDGSE6.jpg',
  },
  {
    id: 3,
    title: '코딩작품3',
    desc: '세번째작업물입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '3',
    img: 'https://cdn.stocksnap.io/img-thumbs/960w/art-people_GWDEXDGSE6.jpg',
  },
  {
    id: 4,
    title: '코딩작품3',
    desc: '세번째작업물입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '3',
    img: 'https://cdn.stocksnap.io/img-thumbs/960w/art-people_GWDEXDGSE6.jpg',
  },
  {
    id: 5,
    title: '코딩작품3',
    desc: '세번째작업물입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '3',
    img: 'https://cdn.stocksnap.io/img-thumbs/960w/art-people_GWDEXDGSE6.jpg',
  },
  {
    id: 6,
    title: '코딩작품3',
    desc: '세번째작업물입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '3',
    img: 'https://cdn.stocksnap.io/img-thumbs/960w/art-people_GWDEXDGSE6.jpg',
  },
];

export default portfolioData;
