const portfolioData = [
  {
    id: 1,
    title: 'VUE 포트폴리오',
    desc: 'VUE 기반 포트폴리오 사이트입니다.',
    skill: 'Vue, Router, CSS, JS',
    role: '개인 작업',
    day: '30',
    img: '/img/Portfolio1.png',
    url: 'https://portfolio-azure-ten-57.vercel.app',
  },
  {
    id: 2,
    title: 'LALA 쇼핑몰',
    desc: 'VUE 기반 쇼핑몰 사이트입니다.',
    skill: 'Vue, Router, CSS, JS',
    role: '팀 작업',
    day: '28',
    img: '/img/pf2.png',
    url: 'https://vue-rara.vercel.app',
  },
  {
    id: 3,
    title: '1:D day 클래스',
    desc: '디자인과 반응형을 담당했습니다.',
    skill: 'React, Router, CSS, JS',
    role: '팀 작업',
    day: '28',
    img: '/img/pf3.png',
    url: 'https://1dday.vercel.app',
  },
  {
    id: 4,
    title: '세미네 부엌',
    desc: '세비네 부엌 리뉴얼 디자인 랜딩페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '14',
    img: '/img/pf4.png',
    url: 'https://semi-nine.vercel.app',
  },
  {
    id: 5,
    title: '디자인플러스',
    desc: '디자인플러스 클론코딩 페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '18',
    img: '/img/pf5.png',
    url: 'https://portfolio2-blond-iota.vercel.app/',
  },
  {
    id: 6,
    title: 'LS그룹',
    desc: 'LS그룹 클론코딩 페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '14',
    img: '/img/pf6.png',
    url: 'https://pf2-one.vercel.app/',
  },
];

export default portfolioData;
