const portfolioData = [
  {
    id: 1,
    title: 'VUE 포트폴리오',
    desc: 'VUE 기반 포트폴리오 사이트입니다.',
    skill: 'Vue, Router, CSS, JS',
    role: '개인 작업',
    day: '30',
    img: '/img/Portfolio1.png',
    url: 'https://portfolio-azure-ten-57.vercel.app',
  },
  {
    id: 2,
    title: 'LALA 쇼핑몰',
    desc: 'MPA 라우팅 및 퍼블리싱을 담당했습니다.',
    skill: 'Vue, Router, CSS, JS',
    role: '팀 작업',
    day: '28',
    img: '/img/pf2.png',
    url: 'https://vue-rara.vercel.app',
  },
  {
    id: 3,
    title: '1:D day 클래스',
    desc: '디자인과 반응형을 담당했습니다.',
    skill: 'React, Router, CSS, JS',
    role: '팀 작업',
    day: '28',
    img: '/img/pf3.png',
    url: 'https://1dday.vercel.app',
  },
  {
    id: 4,
    title: '세미네 부엌',
    desc: '세비네 부엌 리뉴얼 디자인 랜딩페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '14',
    img: '/img/pf4.png',
    url: 'https://semi-nine.vercel.app',
  },
  {
    id: 5,
    title: '디자인플러스',
    desc: '디자인플러스 클론코딩 페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '18',
    img: '/img/pf5.png',
    url: 'https://portfolio2-blond-iota.vercel.app/',
  },
  {
    id: 6,
    title: 'LS그룹',
    desc: 'LS그룹 클론코딩 페이지입니다.',
    skill: 'html, css, js',
    role: '개인 작업',
    day: '14',
    img: '/img/pf6.png',
    url: 'https://pf2-one.vercel.app/',
  },
  {
    id: 7,
    title: 'HB페이퍼',
    desc: 'HB페이퍼 클론코딩 페이지입니다.',
    skill: 'html, css, jquery',
    role: '개인 작업',
    day: '16',
    img: '/img/pf7.png',
    url: 'https://pf3-sand.vercel.app',
  },
  {
    id: 8,
    title: 'todo리스트',
    desc: 'Vue 3 기반으로 제작한 투두리스트입니다.',
    skill: 'Vue 3, css, js',
    role: '개인 작업',
    day: '3',
    img: '/img/pf8.png',
    url: 'https://vue-shop.vercel.app',
  },
  {
    id: 9,
    title: '미니블로그',
    desc: 'Vue 3 기반으로 제작한 모바일용 미니블로그입니다.',
    skill: 'Vue 3, css, js',
    role: '개인 작업',
    day: '4',
    img: '/img/pf9.png',
    url: 'https://mini-blog-three-sigma.vercel.app',
  },
];

export default portfolioData;
